spring:
  datasource:
    url: jdbc:h2:mem:fundamentals
  h2: #default username: sa. default password: none
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      springframework: info
